import React from 'react';
import './FeatureCards.css';

const features = [
  {
    title: 'NFC Check-In',
    description: 'Tap your phone on the classroom tag to instantly validate your attendance using CoreNFC technology.',
    icon: (
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M4 8v8c0 2.2 1.8 4 4 4h8c2.2 0 4-1.8 4-4V8c0-2.2-1.8-4-4-4H8C5.8 4 4 5.8 4 8z"/>
        <path d="M9 10a5.9 5.9 0 0 1 6 0"/>
        <path d="M10.5 13a2.9 2.9 0 0 1 3 0"/>
        <path d="M12 16v.01"/>
      </svg>
    ),
  },
  {
    title: 'QR Code Fallback',
    description: 'No NFC? No problem. Scan the dynamic QR code generated by the teacher to sign in securely.',
    icon: (
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <rect x="3" y="3" width="7" height="7" rx="1"/>
        <rect x="14" y="3" width="7" height="7" rx="1"/>
        <rect x="14" y="14" width="7" height="7" rx="1"/>
        <rect x="3" y="14" width="7" height="7" rx="1"/>
      </svg>
    ),
  },
  {
    title: 'Handwritten Signatures',
    description: 'Sign directly on your screen to confirm your presence. Cryptographically linked to your session.',
    icon: (
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z"/>
        <path d="m15 5 4 4"/>
      </svg>
    ),
  },
  {
    title: 'Real-time Timeline',
    description: 'Keep track of your day with a clear, vertically aligned timeline distinguishing open, upcoming, and completed lectures.',
    icon: (
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <line x1="8" y1="6" x2="21" y2="6"/>
        <line x1="8" y1="12" x2="21" y2="12"/>
        <line x1="8" y1="18" x2="21" y2="18"/>
        <line x1="3" y1="6" x2="3.01" y2="6"/>
        <line x1="3" y1="12" x2="3.01" y2="12"/>
        <line x1="3" y1="18" x2="3.01" y2="18"/>
      </svg>
    ),
  }
];

const FeatureCards = () => {
  return (
    <section className="features-section">
      <div className="container">
        <div className="section-header">
          <h2>Everything you need, built natively.</h2>
          <p>EPISIGN leverages the power of iOS to deliver a seamless, secure, and fast attendance experience.</p>
        </div>
        <div className="features-grid">
          {features.map((feature, idx) => (
            <div key={idx} className="card feature-card">
              <div className="feature-icon">{feature.icon}</div>
              <h3>{feature.title}</h3>
              <p>{feature.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default FeatureCards;
